# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Update surge configure file

on:
  workflow_dispatch: # 手动触发
  schedule: # 每隔5天触发一次
    - cron: '0 9 */5 * *'
  push: # 手动添加域名时触发
    paths:
      - 'custom.conf'
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: write

jobs:
  update-surge-configure-file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Update
      run: |
        python ./main.py -c custom.conf
        git add surge.conf
    - name: Generate ruleset
      run: |
        sed -i "s#^\.##g" ./surge.conf
        awk '{print "DOMAIN-SUFFIX,"$0}' surge.conf > surge_gfwlist.list
    - name: Commit files
      run: |
         git config --local user.email "ciaoly@github.com"
         git config --local user.name "ciaoly"
         git add surge_gfwlist.list
         git commit -m "更新于$(date "+%Y-%m-%d %H:%M:%S")"
         
    # 更新至远程github代码仓库中
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GFWLIST_GIT_KEY }}
         branch: master
